; Common Contraction Hotstrings
;::im::I'm
;::ive::I've
;::dont::don't
;::cant::can`t
;::wont::won't
;::shouldnt::shouldn't
;::wouldnt::wouldn't
;::couldnt::couldn't
;::isnt::isn't
;::arent::aren't
;::wasnt::wasn't
;::werent::weren't
;::hasnt::hasn't
;::havent::haven't
;::doesnt::doesn't
;::didnt::didn't
;::theres::there's
;::heres::here's
;::whos::who's
;::thats::that's
;::itll::it'll
;::wholl::who'll
;::well::we'll
;::youll::you'll
;::theyll::they'll
;::id::I'd
;::hed::he'd
;::shed::she'd
;::youd::you'd
;::theyd::they'd
;::ill::I'll
;::wheres::where's
;::whats::what's
::superintendant::superintendent